---

- name: Prepare step for vsftpd
  block:
    - name: create directory for vsftpd files
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root
